-- The original Version 1 schema allowed anonymous users to read every order
-- and update order statuses. It has intentionally been retired.
--
-- For both existing and new Supabase projects, run the complete idempotent SQL
-- in supabase-security-migration.sql instead. That file creates any missing
-- tables and applies the secure Auth, RLS, RPC, menu, and Realtime setup.
